// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var HooksPage$BsReactNativeNextDemo = require("./HooksPage.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(HooksPage$BsReactNativeNextDemo.make, {
          message: "Hello!"
        }), "index");

/*  Not a pure module */
